### Get Users
GET http://127.0.0.1:5055/users

### Create User
POST http://127.0.0.1:5055/users
Content-Type: application/json

{
  "name": "erin",
  "email": "erin2@example.com",
  "password": "newpassword123"
}

### Delete User
DELETE http://127.0.0.1:5055/users 
Content-Type: application/json

{
  "id": "6a0711b60df90172abaef73d"
}

### Update User
PUT http://127.0.0.1:5055/users
Content-Type: application/json

{
  "columnName": "password",
  "email": "catherine@example.com",
  "columnValue": "newpassword456"
}

### Login User
POST http://127.0.0.1:5055/users/login
Content-Type: application/json

{
  "email": "jayson@example.com",
  "password": "newpassword456"
}
